app/models.py
from . import db
from . import login_manager
from flask_login import UserMixin
from . import login_manager
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    email=db.Column(db.String(255),unique = True)
    password=db.Column(db.String(255))
    username = db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

     
class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer,primary_key=True)
    post = db.Column(db.String(255))
    category = db.Column(db.String(255))
    title = db.Column(db.String(255))
    vote_count = db.Column(db.Integer)
    added_date = db.Column(db.DateTime,default=datetime.utcnow)
    author = db.Column(db.Integer,db.ForeignKey('users.id'))


    def save(self):
        db.session.add(self)
        db.session.commit()
    def delete(self):
        db.session.delete(self)
        db.session.commit()
    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"    


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.Text(), nullable = False)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    
    def save_comment(self):
        db.session.add(self)
        db.session.commit()
    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()
    def __repr__(self):
        return f'Comment: {self.comment}'
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms import validators
from wtforms.validators import DataRequired

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you:',validators = [DataRequired()])
    submit = SubmitField('Submit')

class PostForm(FlaskForm):
  title = StringField(' title:',validators=[DataRequired()]) 
  post = StringField(' post:',validators=[DataRequired()]) 
  username= StringField(' username:',validators=[DataRequired()])
  category = SelectField("Choose your desired category:",choices=[('interview_pitch','interview_pitch'),('pickup_lines','pickup_lines'),('product_pitch','product_pitch'),('promotion_pitch','promotion_pitch'),('Humour_pitch','Humour_pitch')])

  submit = SubmitField('Submit')
                                                                    
  

class CommentForm(FlaskForm):
  comment = TextAreaField('Add a Comment:',validators=[DataRequired()])
  username= StringField(' Name:',validators=[DataRequired()])
  submit = SubmitField(' Submit') 

app/__init__.py
from flask import Flask
import os
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_simplemde import SimpleMDE

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
photos = UploadSet('photos',IMAGES)
from flask_mail import Mail
mail = Mail()
simple = SimpleMDE()
def create_app(config_name):

    app = Flask(__name__)
    


    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)
    app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get("DATABASE_URL")
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    bootstrap.init_app(app)
    db.init_app(app)
    with app.app_context():
        # Extensions like Flask-SQLAlchemy now know what the "current" app
        # is while within this block. Therefore, you can now run........
        db.create_all()
    # configure UploadSet
    configure_uploads(app,photos)

    mail.init_app(app)
    simple.init_app(app)

  
    from .models import User
    
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    # Will add the views and forms
    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from .forms import UpdateProfile, CommentForm, PostForm
from flask_login import login_required, current_user
from . import main
from ..models import  User ,Post, Comment
from .. import db,photos
from flask.helpers import flash
@main.route('/')
def index():
    
    pickup_lines= Post.query.filter_by(category='pickup_lines').all()
    interview_pitch = Post.query.filter_by(category='interview_pitch').all()
    product_pitch= Post.query.filter_by(category='product_pitch').all()
    promotion_pitch = Post.query.filter_by(category='promotion_pitch').all()
    Humour_pitch = Post.query.filter_by(category='Humour_pitch').all()
    posts = Post.query.order_by(Post.added_date.desc()).all()
    return render_template('index.html',interview_pitch=interview_pitch, pickup_lines=pickup_lines,  product_pitch= product_pitch,promotion_pitch=promotion_pitch,Humour_pitch=Humour_pitch, posts=posts)

@main.route('/posts')
@login_required
def posts():
    posts = Post.query.all()
    user = current_user
    return render_template('pitches.html', posts=posts, user=user)

@main.route('/user/<uname>')
@login_required
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    '''
    View root page function that returns the index page and its data
    '''
    
    
    return render_template('profile/profile.html',user = user)    

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))    



@main.route('/comment/<int:post_id>', methods=['GET', 'POST'])
@login_required
def comment(post_id):
    form = CommentForm()
    post = Post.query.get(post_id)
    user = User.query.all()
    comments = Comment.query.filter_by(post_id=post_id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        post_id = post_id
        user_id = current_user._get_current_object().id
        new_comment = Comment(
            comment=comment,
            post_id=post_id,
            user_id=user_id
        )
        new_comment.save_comment()
        new_comments = [new_comment]
        print(new_comments)
        flash('Your comment has been created successfully!')
        return redirect(url_for('.comment', post_id=post_id))
    return render_template('comments.html', form=form, post=post, comments=comments, user=user)

@main.route('/new_post', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        post = form.post.data
        category = form.category.data
        user_id = current_user._get_current_object().id
        # post_obj = Post(post=post, title=title, category=category, user_id=user_id)
        new_post=Post(title=title,post=post,category=category)
        new_post.save()
        db.session.add(new_post)
        db.session.commit()
        # post_obj.save()
        flash('Your pitch has been created successfully!')
        return redirect(url_for('main.index',uname=current_user.username))
    return render_template('recent_pitch.html', form=form ,title='Pitch Perfect')

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css')}}">
    
    {% if title %}
    <title>Pitch-App</title>
    {% else %}
    <title>Pitch-Perfect</title>
    {% endif %}
  </head>
  <body>
    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock %} 


    {% block content %}
    {% endblock %}


</body>
</html>

app/templates/comments.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

<!-- {{ wtf.quick_form(form) }} -->


<div class="container">


    <div class="row">


        <div class="col-md-6 ">
            {{ wtf.quick_form(form) }}


        </div>
        <div class="col-md-6">
            <div class="row">
                {% for comment in comments%}
                <div class="col-md-12">
                    <div class="card w-50 mt-3">
                        <div class="card-body">
                            <h5 class="card-title"></h5>
                            <p class="card-text">{{comment.comment}}</p>

                        </div>
                    </div>
                </div>

                {% endfor%}

            </div>
        </div>
    </div>

</div>


{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import "macros.html" as macro %}
{% block content %}

<div class="card m-5">
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  <div class="alert alert-{{ category }} d-flex align-items-center mt-4" role="alert">
  

      <div>
          {{ message }}
      </div>
  </div>
  {% endfor %}
  {% endif %}
  {% endwith %}

</div>

<div class="text-center">
  <h3 style="color: black;" >PRODUCT PITCHES</h3>
  <div class="row">
<ul>
  {{macro.display_post(product_pitch)}}
</ul>
</div>
</div>

<div class="text-center"><h3 style="color: black;">PICKUP LINE PITCHES </h3>
  <div class="row">
  <ul>
    {{macro.display_post(pickup_lines)}}
  </ul>
</div>
</div>


<div class="text-center"><h3 style="color: black;">INTERVIEW PITCHES</h3>
  <div class="row">
  <ul>
    {{macro.display_post(interview_pitch)}}
  </ul>
</div>
</div>


<div class="text-center"><h3 style="color: black;">HUMOUR PITCHES</h3>
  <div class="row">
  <ul>
    {{macro.display_post(Humour_pitch)}}
  </ul>
</div>
</div>


<div class="text-center">
  <h3 style="color: black;"> PROMOTION PITCHES</h3>
  <div class="row">
<ul>
  {{macro.display_post(promotion_pitch)}}
</ul>

</div>
</div>
{% endblock %}

app/templates/macros.html
{% macro display_post(posts)%}



{% for post in posts%}
<div class="col-md-3" >
    <div class="card  mb-3" id="card1" style="background-color:#1E5128;color: aliceblue;" >
        
        <div class="card-header">{{post.title}}</div>
        <div class="card-body">
            <h5 class="card-title">{{post.category}}</h5>

            <p class="card-text">{{post.added_date.strftime('%b %d, %Y')}}</p>
            <p class="card-text" style="font-family: 'IM Fell English', serif;">{{post.post}}</p>
               
            <a href="{{url_for('main.comment',post_id=post.id)}}" class="btn btn-secondary">Leave a Comment..</a>
            <div class="voting">
                <button id="likebtn">
                    <i class="fa fa-thumbs-up"></i>
                </button>
                <input type="number" id="input1" value="0" name="" min="0">
                
                <button id="dislikebtn">
                    <i class="fa fa-thumbs-down"></i>
                </button>
                <input type="number" id="input2" value="0" name="" min="0">

                </div>

                <style>
                 input{
                     width: 50px;
                     border: none;
                     background: none;
                     color: #919191;
                     font-size: 20px;
                     margin: 0 5px;
                 }
                 button{
                     color: #fff;
                     background:none ;
                     border: none;
                     font-size: 20px;
                     padding: 0 5px;
                     margin: 10px 0;
                     margin-left: 10px;
                     cursor: pointer;
                 }
                 button:active{

                    color: #004eff;
                    transform: scale(1,2);
                 }
                    
                </style>
                <script type="text/javascript">
                 let likebtn=document.querySelector('#likebtn')
                 let dislikebtn=document.querySelector('#dislikebtn')


                 let input1=document.querySelector('#input1')
                 let input2=document.querySelector('#input2')
                 likebtn.addEventListener('click',()=>{
                     input1.value=parseInt(input1.value)+1;
                     input1.style.color='#12ff00'
                 })
                 dislikebtn.addEventListener('click',()=>{
                     input2.value=parseInt(input2.value)+1;
                     input2.style.color='#ff0000'
                 })

                </script>
        </div>
    </div>
</div>



{% endfor %}





{% endmacro %}

app/templates/navbar.html
<div class="hero-head">
    <nav class="navbar is-dark">
        <div class="container">
            <a class="navbar-brand" href="/" style="color: #D9CAB3 ;"> PITCHES</a>
            <div id="navbarMenuHeroA" class="navbar-menu">
                <div class="navbar-end">
                    <a href="{{ url_for('main.index') }}" class="navbar-item">
                        Home
                    </a>
                    {% if current_user.is_authenticated %}
                    <a href="{{ url_for('main.profile',uname=current_user.username) }}" class="navbar-item">
                        Profile
                    </a>
                    {% endif %}
                    {% if not current_user.is_authenticated %}
                    <a href="{{ url_for('auth.login') }}" class="navbar-item">
                        Login
                    </a>
                    <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                        Sign Up
                    </a>
                    {% endif %}
                    {% if current_user.is_authenticated %}
                    <a class="navbar-item"href="{{url_for('main.new_post')}}">Add-Pitch</a>
                    <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                        Logout
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</div>

app/templates/profile/profile.html
{% extends "base.html" %}
{% import "macros.html" as macro %}
{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
      <a href="{{url_for('main.update_profile',uname =user.username)}}">Edit profile</a>
    {% endif %}
  </div>


  <!--Display profile photo-->
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">

    {%else%}
    <p>No profile picture</p>
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
    {% endif %}

     
  </div>
</div>
</div>
<div class=" container row">
  {{macro.display_post(posts)}}
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/recent_pitch.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container-fluid">
    

    
    <div class="row">


        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }} d-flex align-items-center" role="alert">
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img"
                aria-label="{{ category }}:">
                <use xlink:href="#exclamation-triangle-fill" />
            </svg>
            <div>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}    
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div id="pitch-app">
            </div>
            {{wtf.quick_form(form)}}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}